### ISSUE TITLE
ERROR:  container is not an agtype array when SET with map

### ISSUE THREAD

**Issue by deem0n** [apache/incubator-age#137] opened 2021-11-03 10:01 UTC
```sql
SELECT *
FROM cypher('test', $$
    MATCH (v :Person)
    where id(v) = 844424930131969
    SET v.config = {first: 123, second: {a: 321}}
    RETURN v
$$) as (v agtype);
ERROR:  container is not an agtype array
```

But, if you enclose map into array, then magically first element of the array will be used as value for the assignment:

```sql
SELECT *
FROM cypher('test', $$
    MATCH (v :Person)
    where id(v) = 844424930131969
    SET v.config = [{first: 1, second: {a: 3}}, 'skipped', 'also skipped']
    RETURN v
$$) as (v agtype);

{"id": 844424930131969, "label": "Person", "properties": {"name": "Andres", "title": "Developer", "config": {"first": 1, "second": {"a": 3}}}}::vertex
```

--------
here is full log of steps:

```
select create_graph('test');
NOTICE:  graph "test" has been created
┌──────────────┐
 │ create_graph │
├──────────────┤
 │              │
└──────────────┘
(1 row)


SELECT * 
FROM cypher('test', $$
    CREATE (:Person {name: 'Andres', title: 'Developer', config: {first: 123, second: {a:321}}})
$$) as (n agtype);


SELECT * FROM cypher('test', $$
MATCH (v)
RETURN v
$$) as (v agtype);

{"id": 844424930131969, "label": "Person", "properties": {"name": "Andres", "title": "Developer", "config": {"first": 123, "second": {"a": 321}}}}::vertex


SELECT *
FROM cypher('test', $$
    WITH {first: 123, second: {a: 321}} AS m
    MATCH (v :Person)
    where id(v) = 844424930131969
    SET v.config = m
    RETURN v
$$) as (v agtype);
ERROR:  container is not an agtype array


SELECT *
FROM cypher('test', $$
    MATCH (v :Person)
    where id(v) = 844424930131969
    SET v.config = {first: 123, second: {a: 321}}
    RETURN v
$$) as (v agtype);
ERROR:  container is not an agtype array


SELECT *
FROM cypher('test', $$
    MATCH (v :Person)
    where id(v) = 844424930131969
    SET v.config = [{first: 1, second: {a: 3}}]
    RETURN v
$$) as (v agtype);

{"id": 844424930131969, "label": "Person", "properties": {"name": "Andres", "title": "Developer", "config": {"first": 1, "second": {"a": 3}}}}::vertex
```

**Comment by JoshInnis** [comment] 2021-11-03 18:42
Issue has same root cause as https://github.com/apache/incubator-age/issues/44. Currently using maps and list in the SET clause are not properly supported. We will investigate solutions for this.

**Comment by deem0n** [comment] 2021-11-03 19:50
Currently I use `SET v.config = [{first: 1, second: {a: 3}}]` hack. Will switch to normal syntax once fixed. Thanks!

**Comment by pdpotter** [comment] 2022-04-22 10:22
This issue is now fixed on master (by commit https://github.com/apache/incubator-age/commit/ab70781b4b311922f14f2bcb1b2144f1df9a9da1).

**Closed** 2022-04-27 07:24 UTC
Labels: bug
